import { postQuantumSchemes, schemeName } from "../config/schemes.ts";
import type { RahoState } from "../lib/raho/types.ts";
import { esc } from "../shared/dom.ts";

export type Route = "overview" | "migrate" | "accounts" | "keys" | "history" | "settings";
export const routes: { id: Route; label: string; glyph: string }[] = [
  { id: "overview", label: "Overview", glyph: "◫" }, { id: "migrate", label: "Migrate", glyph: "↗" },
  { id: "accounts", label: "Accounts", glyph: "◎" }, { id: "keys", label: "Keys", glyph: "⌘" },
  { id: "history", label: "History", glyph: "◷" }, { id: "settings", label: "Settings", glyph: "⚙" },
];

const row = (label: string, value: string, tone = "") => `<div class="rm-row"><span>${esc(label)}</span><strong class="${tone}">${esc(value)}</strong></div>`;
const panel = (kicker: string, title: string, content: string, extra = "") =>
  `<section class="rm-panel ${extra}"><div class="rm-panel__head"><span class="rh-kicker">${esc(kicker)}</span><h2 class="rh-subhead">${esc(title)}</h2></div>${content}</section>`;
const action = (id: string, label: string, secondary = false) => `<button type="button" class="rh-btn ${secondary ? "rh-btn--ghost" : ""}" data-flow="${id}">${esc(label)} <span aria-hidden="true">↗</span></button>`;
const link = (route: Route, label: string) => `<a class="rh-btn rh-btn--ghost" href="#/${route}">${esc(label)} <span aria-hidden="true">↗</span></a>`;
const schemeOptions = (selected: string) => postQuantumSchemes.map((s) => `<option value="${s.id}" ${selected === s.id ? "selected" : ""}>${esc(s.name)}</option>`).join("");
const stageLabel = (stage: RahoState["stage"]) => ({ NOT_STARTED: "Not started", DETECTED: "Detected", KEY_PREPARED: "Key prepared", COMPATIBLE: "Compatible", BUILT: "Built", READY: "Ready", SUBMITTED: "Demo executed", VERIFYING: "Demo verified", ACTIVE: "Post quantum active", FAILED: "Action required" })[stage];
const date = (value?: string) => value ? new Date(value).toLocaleString() : "Not available";

export const lifecycle = ["Account", "Detect", "Prepare Key", "Compatibility", "Build", "Execute", "Verify", "Activate"];
export const progress = (state: RahoState) => {
  const index = ({ NOT_STARTED: 0, DETECTED: 1, KEY_PREPARED: 2, COMPATIBLE: 3, BUILT: 4, READY: 5, SUBMITTED: 6, VERIFYING: 7, ACTIVE: 8, FAILED: 0 })[state.stage];
  return `<ol class="rm-progress" aria-label="Migration lifecycle">${lifecycle.map((label, i) => `<li class="${i < index ? "is-done" : i === index ? "is-current" : ""}" ${i === index ? 'aria-current="step"' : ""}><span>${String(i + 1).padStart(2, "0")}</span><strong>${label}</strong></li>`).join("")}</ol>`;
};

export function overview(state: RahoState): string {
  const active = state.stage === "ACTIVE";
  return `<div class="rm-page">
    <section class="rm-hero"><span class="rh-kicker">POST QUANTUM SMART ACCOUNT MIGRATION LAYER</span><h2>${active ? "Post quantum active." : "Move accounts forward."}</h2><p>${active ? "Your demo migration is complete." : "Detect. Prepare. Migrate. Verify."}</p>${link("migrate", active ? "View migration" : "Start migration")}<div class="rm-hero__orbit" aria-hidden="true"><i></i><i></i><i></i></div></section>
    <div class="rm-grid rm-grid--three">
      ${panel("ACCOUNT", "Current account", row("Account", state.account.address) + row("Network", state.account.network) + row("Type", state.account.accountType) + row("Authentication", state.account.authentication))}
      ${panel("MIGRATION", "Transition status", row("State", stageLabel(state.stage), active ? "rm-positive" : "") + row("Compatibility", state.compatibility?.status ?? "Pending") + row("Last verification", date(state.verification?.verifiedAt)))}
      ${panel("KEY", "Post quantum path", row("Scheme", state.key ? schemeName(state.key.schemeId) : "Not selected") + row("Key", state.key?.status ?? "Not prepared") + row("History", `${state.history.length} demo record${state.history.length === 1 ? "" : "s"}`))}
    </div>${panel("LIFECYCLE", "Migration path", progress(state) + `<div class="rm-panel__foot">${link("migrate", "Open migration")}</div>`, "rm-panel--wide")}</div>`;
}

function compatibility(state: RahoState): string {
  const checks = state.compatibility?.checks ?? ["Account supported", "Authentication detected", "Migration module available", "PQ key prepared", "Network compatible", "Migration path available"].map((label) => ({ label, status: "pending" }));
  return `<div class="rm-checks">${checks.map((check) => `<div><span class="rm-check-dot ${check.status}"></span><span>${esc(check.label)}</span><strong>${check.status === "compatible" ? "Compatible" : "Pending"}</strong></div>`).join("")}</div>`;
}

export function migrate(state: RahoState): string {
  const s = state.stage;
  const account = state.account;
  let content = "";
  if (s === "NOT_STARTED") content = panel("01 / ACCOUNT", "Select account", `<p class="rm-note">The account and authentication below are controlled demo data. You can also connect a wallet for its address.</p><div class="rm-data">${row("Account", account.address)}${row("Network", account.network)}${row("Account type", account.accountType)}</div><div class="rm-panel__foot">${action("detect", "Detect authentication")}</div>`);
  if (s === "DETECTED") content = panel("02 / DETECT", "Authentication detected", `<div class="rm-auth"><div><span>Current authentication</span><strong>${esc(account.authentication)}</strong><small>Demo detection</small></div><div class="rm-auth__arrow">→</div><div><span>Next path</span><strong>Post Quantum</strong><small>Prepare a new key</small></div></div><div class="rm-data">${row("Account", account.address)}${row("Key type", account.keyType)}${row("Status", "Detected")}</div><label class="rm-select-label" for="scheme">Signature scheme</label><select class="rh-select" id="scheme">${schemeOptions(state.selectedSchemeId)}</select><p class="rm-note">Scheme options are conceptual. No cryptographic key is generated in demo mode.</p><div class="rm-panel__foot">${action("prepare", "Prepare PQ key")}</div>`);
  if (s === "KEY_PREPARED") content = panel("03 / PREPARE", "Key path prepared", `<div class="rm-data">${row("Signature scheme", schemeName(state.key!.schemeId))}${row("Key status", "Prepared in demo")}${row("Public key", state.key!.publicKey)}${row("Created", date(state.key!.createdAt))}</div><p class="rm-note">No key material was generated or registered onchain.</p><div class="rm-panel__foot">${action("compatibility", "Check compatibility")}</div>`);
  if (s === "COMPATIBLE") content = panel("04 / COMPATIBILITY", "Migration ready", `${compatibility(state)}<p class="rm-note">Demo compatibility uses controlled local results.</p><div class="rm-panel__foot">${action("build", "Build migration")}</div>`);
  if (s === "BUILT") content = panel("05 / BUILD", "Migration constructed", `<div class="rm-auth"><div><span>Current authentication</span><strong>${esc(state.request!.currentAuth)}</strong></div><div class="rm-auth__arrow">→</div><div><span>New authentication</span><strong>${esc(state.request!.newAuth)}</strong></div></div><div class="rm-data">${row("Account", account.address)}${row("PQ key", state.request!.publicKey)}${row("Method", state.request!.method)}${row("Network", account.network)}${row("Estimated fee", state.request!.estimatedFee)}${row("Build status", "Built locally")}</div><div class="rm-panel__foot">${action("review", "Review migration")}</div>`);
  if (s === "READY") content = panel("06 / REVIEW", "Confirm the transition", `<p class="rm-note">This changes the account's authentication authority in the proposed migration. Demo execution changes local UI state only.</p><div class="rm-auth rm-auth--review"><div><span>Current authentication</span><strong>${esc(state.request!.currentAuth)}</strong></div><div class="rm-auth__arrow">→</div><div><span>New authentication</span><strong>${esc(state.request!.newAuth)}</strong></div></div><div class="rm-data">${row("Account", account.address)}${row("New key", state.request!.publicKey)}${row("Migration method", state.request!.method)}${row("Network", account.network)}${row("Status", "Ready for demo execution")}</div><div class="rm-panel__foot">${action("execute", "Execute demo migration")}</div>`);
  if (s === "SUBMITTED") content = panel("07 / EXECUTE", "Demo execution recorded", `<div class="rm-signal"><span></span><strong>Local state advanced</strong></div><p class="rm-note">Nothing was submitted to a wallet or blockchain. No transaction hash exists.</p><div class="rm-panel__foot">${action("verify", "Run demo verification")}</div>`);
  if (s === "VERIFYING") content = panel("08 / VERIFY", "Transition verified in demo", `<div class="rm-checks">${state.verification!.checks.map((c) => `<div><span class="rm-check-dot compatible"></span><span>${esc(c)}</span><strong>Demo pass</strong></div>`).join("")}</div><p class="rm-note">These checks represent the future verification interface. No cryptographic or onchain verification ran.</p><div class="rm-panel__foot">${action("activate", "Activate PQ authentication")}</div>`);
  if (s === "ACTIVE") content = panel("09 / ACTIVE", "Post Quantum Authentication Active", `<div class="rm-active-orb" aria-hidden="true"><span></span></div><div class="rm-data">${row("Account", account.address)}${row("Authentication scheme", account.authentication)}${row("Key status", "Demo registered")}${row("Migration date", date(state.history[0]?.timestamp))}${row("Verification", "Demo verified")}</div><p class="rm-note">This is a local demonstration. The account has not changed onchain.</p><div class="rm-panel__foot">${link("keys", "View keys")}${link("history", "View history")}</div>`);
  return `<div class="rm-page"><div class="rm-heading"><span class="rh-kicker">GUIDED MIGRATION / DEMO</span><h2>Account to post quantum.</h2><p>One clear path. Every state visible.</p></div>${progress(state)}<div class="rm-wizard">${content}<aside class="rm-aside">${panel("MIGRATION STATUS", stageLabel(s), `<div class="rm-data">${row("Account", account.address)}${row("Authentication", account.authentication)}${row("PQ key", state.key?.status ?? "Pending")}${row("Compatibility", state.compatibility?.status ?? "Pending")}${row("Execution", s === "SUBMITTED" || s === "VERIFYING" || s === "ACTIVE" ? "Demo only" : "Pending")}</div><p class="rm-note">Local demonstration. No wallet signing or chain activity.</p>`)}</aside></div></div>`;
}

export function accounts(state: RahoState): string { return `<div class="rm-page"><div class="rm-heading"><span class="rh-kicker">ACCOUNTS</span><h2>Authentication, visible.</h2><p>Current authority and migration status.</p></div><div class="rm-grid rm-grid--two">${panel("SELECTED ACCOUNT", "Account profile", `<div class="rm-data">${row("Account", state.account.address)}${row("Network", state.account.network)}${row("Account type", state.account.accountType)}${row("Authentication scheme", state.account.authentication)}${row("Key type", state.account.keyType)}${row("Source", state.account.source === "demo" ? "Controlled demo data" : "Wallet address with demo metadata")}</div><div class="rm-panel__foot">${link("migrate", "Open migration")}</div>`)}${panel("DETECTION", "Current state", `<div class="rm-detection"><span class="rm-detection__ring"></span><strong>${esc(stageLabel(state.stage))}</strong><small>${state.stage === "NOT_STARTED" ? "Run demo detection to continue" : "Demo authentication state"}</small></div>${state.stage === "NOT_STARTED" ? `<div class="rm-panel__foot">${action("detect", "Detect authentication")}</div>` : ""}`)}</div></div>`; }

export function keys(state: RahoState): string { return `<div class="rm-page"><div class="rm-heading"><span class="rh-kicker">KEYS</span><h2>Prepare. Register. Rotate.</h2><p>Scheme choices remain open.</p></div><div class="rm-grid rm-grid--two">${panel("CURRENT KEY", "Post quantum key", `<div class="rm-data">${row("Scheme", state.key ? schemeName(state.key.schemeId) : "Not selected")}${row("Status", state.key?.status === "registered" ? "Demo registered" : state.key?.status === "prepared" ? "Prepared in demo" : "Not prepared")}${row("Public key", state.key?.publicKey ?? "Not available")}${row("Created at", date(state.key?.createdAt))}</div><div class="rm-panel__foot">${link("migrate", state.key ? "View migration" : "Prepare key")}</div>`)}${panel("KEY ROTATION", "Prepare a replacement", `<p class="rm-note">Rotation is available after activation. This prepares a local demo intent only.</p><label class="rm-select-label" for="rotation-scheme">New scheme</label><select class="rh-select" id="rotation-scheme" ${state.stage !== "ACTIVE" ? "disabled" : ""}>${schemeOptions(state.rotation?.schemeId ?? state.key?.schemeId ?? state.selectedSchemeId)}</select><div class="rm-data">${row("Current key", state.key?.status ?? "Not available")}${row("New key", state.rotation ? schemeName(state.rotation.schemeId) : "Not prepared")}${row("Compatibility", state.stage === "ACTIVE" ? "Demo compatible" : "Awaiting activation")}${row("Rotation status", state.rotation?.status ?? "Not started")}</div><div class="rm-panel__foot"><button type="button" class="rh-btn" data-flow="rotate" ${state.stage !== "ACTIVE" ? "disabled" : ""}>Prepare rotation <span aria-hidden="true">↗</span></button></div>`)}</div></div>`; }

export function history(state: RahoState): string { return `<div class="rm-page"><div class="rm-heading"><span class="rh-kicker">HISTORY</span><h2>Migration audit trail.</h2><p>Local demo records only.</p></div>${panel("MIGRATION RECORDS", `${state.history.length} demo record${state.history.length === 1 ? "" : "s"}`, state.history.length ? `<div class="rm-history">${state.history.map((record) => `<article><div><span>ACCOUNT</span><strong>${esc(record.account)}</strong></div><div><span>TRANSITION</span><strong>${esc(record.previousAuth)} → ${esc(record.newAuth)}</strong></div><div><span>NETWORK</span><strong>${esc(record.network)}</strong></div><div><span>STATUS</span><strong>Demo active</strong></div><div><span>VERIFICATION</span><strong>Demo verified</strong></div><div><span>TIME</span><strong>${esc(date(record.timestamp))}</strong></div></article>`).join("")}</div>` : `<div class="rm-empty">No migration records yet.<br><span>Complete the demo flow to create one.</span></div><div class="rm-panel__foot">${link("migrate", "Start migration")}</div>`)}</div>`; }

export function settings(state: RahoState): string { return `<div class="rm-page"><div class="rm-heading"><span class="rh-kicker">SETTINGS</span><h2>Integration status.</h2><p>Deployment configuration lives in one place.</p></div><div class="rm-grid rm-grid--two">${panel("ENVIRONMENT", "Demo mode", `<div class="rm-data">${row("Contracts", "Not deployed")}${row("Chain", "Not configured")}${row("Transactions", "Never submitted")}${row("Account", state.account.address)}</div><p class="rm-note">Future deployment values are read from src/config. The UI uses the Raho adapter interface.</p>`)}${panel("LOCAL DATA", "Reset demonstration", `<p class="rm-note">Clear the current migration and local history in this browser.</p><div class="rm-panel__foot">${action("reset", "Reset demo", true)}</div>`)}</div></div>`; }

export const renderView = (route: Route, state: RahoState): string => ({ overview, migrate, accounts, keys, history, settings })[route](state);
